version: "3.9"

services:
  frontend:
    container_name: frontend
    image: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend:/app
    
  backend:
    container_name: backend
    image: go
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    #ports:
    #  - 
    volumes:
      - ./backend:/opt/app/api

  rabbitMQ:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management
    ports:
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  frontend:
  rabbitmq: